### ISSUE TITLE
Score needs to identify the agent providing score inputs

### ISSUE THREAD

**Issue by paulakeen** [isa-camss/CAV#21] opened 2020-11-16 11:17 UTC
The current CAV model defines the following axiom: "cav:Score cav:isProvidedBy foaf:Agent". This works fine when an Evaluator, for example, provides manually the score, e.g. a teacher that reads a pupil's exam and scores manually the exam. However, in the situation where the score is calculated, based on a formula or an algorithm with different formulae, what is provided by the evaluator is not the score, but an initial "input" value that is used by the formular to produce the score. 

This has been made obvious when developing the MS IT pilot, where the evaluator provides "comparison values" between all the lots tendered as inputs for the ELECTRE algorithm to calculate the different scores per criterion, lot and tenderer.

To solve this we see two possibilities:

1) Add to the CAV the axiom "foaf:Agent cav:providesScoreInput cav:Score". This would transform the cav:Score class in a reification involving (compulsorily) the input rdf:Resource (as depicted currently in the CAV).
2) Implement an ad-hoc reification class in the pilot's namespace based on the pattern introduced recently by ePO, e.g. a reification class named, for example, "EvaluationComparisonValueAssignation" (subclass of epo:ProcurementSituation), involving the role (Evaluator), the agent (the person behind the role Evaluator), the comparison value (e.g. A2, B3, D4, see dataset provided by IT), the Criterion (an AwardCriterion, in the case of the pilot. The Lot is accessible via the Criterion).

The figure below illustrates the 1st proposal, to add a property to CAV:

![CAV](https://user-images.githubusercontent.com/16134316/99293718-4e821580-2843-11eb-8736-d898c176be0f.png)

**Comment by jseguraf** [comment] 2020-11-24 17:02
The WG agrees with this proposal. Since no other public opinions have been issued, the issue is closed.

**Comment by hricolor** [comment] 2020-11-25 16:16
@paulakeen, as agreed with you and @jseguraf we withdraw this issue, since whilst working with the CAV pilot for Italy's Anticorruzione Use Case we realised that this can be approached differently, and with no impact on the Core Vocabulary (CAV). Therefore, this is a good reason for closing this issue. Once the solution stable in the pilot, we will come back to this comment and we will illustrate what the solution consists in.

**Closed as completed by hricolor** 2020-11-25 16:16 UTC
